SELECT * FROM EMPLOYEES;

 SELECT * FROM EMPLOYEES WHERE DEPARTMENT_ID = 60 OR DEPARTMENT_ID = 90;

SELECT * FROM EMPLOYEES WHERE JOB_ID = 'IT_PROG';

--Display the average salary for 'IT_GROUP';
SELECT AVG(SALARY) FROM EMPLOYEES WHERE JOB_ID = 'IT_PROG'; -- Here we found what is the average salary for the employees who work an IT_PROGRAM job

SELECT MAX(SALARY) FROM EMPLOYEES WHERE JOB_ID = 'IT_PROG'; -- Here we found what is the max salary for the employees who work an IT_PROGRAM job

SELECT MIN(SALARY) FROM EMPLOYEES WHERE JOB_ID = 'IT_PROG'; -- Here we found what is the min salary for the employees who work an IT_PROGRAM job

--Display average salary for 'SA_REP' --> THIS IS AN INTERVIEW QUESTION
SELECT * FROM EMPLOYEES
WHERE JOB_ID IN ('IT_PROG','SA_REP');

SELECT * FROM EMPLOYEES
WHERE JOB_ID = 'SA_REP';

SELECT AVG(SALARY) FROM EMPLOYEES
WHERE JOB_ID = 'SA_REP';


-------------------------------------------------------------------------------------------------------------------------------------------------
--NOTE: whenever, you see that in the question it says EACH and asks also for aggregate functions(sum, min, max, avg), that means use GROUP BY

SELECT DISTINCT JOB_ID FROM EMPLOYEES;
--OR
SELECT JOB_ID FROM EMPLOYEES
GROUP BY JOB_ID; --Will use the group by when i want to find an average or a minimum for that group

SELECT * FROM EMPLOYEES;

SELECT JOB_ID, AVG(SALARY) FROM EMPLOYEES GROUP BY JOB_ID; -- THIS WILL SHOW ME A LIST OF THE JOB_ID WITHOUT DUPLICATES AND THE AVERAGE SALARY FOR EACH ONE OF THEM
SELECT JOB_ID, MAX(SALARY) FROM EMPLOYEES GROUP BY JOB_ID; -- THIS WILL SHOW ME A LIST OF THE JOB_ID WITHOUT DUPLICATES AND THE MAX SALARY FOR EACH ONE OF THEM
SELECT JOB_ID, MIN(SALARY) FROM EMPLOYEES GROUP BY JOB_ID; -- THIS WILL SHOW ME A LIST OF THE JOB_ID WITHOUT DUPLICATES AND THE MIN SALARY FOR EACH ONE OF THEM
SELECT JOB_ID, SUM(SALARY) FROM EMPLOYEES GROUP BY JOB_ID; -- THIS WILL SHOW ME A LIST OF THE JOB_ID WITHOUT DUPLICATES AND THE MIN SALARY FOR EACH ONE OF THEM
SELECT JOB_ID, AVG(SALARY), MAX(SALARY), MIN(SALARY) FROM EMPLOYEES GROUP BY JOB_ID; -- THIS WILL SHOW ME A LIST OF THE JOB_ID WITHOUT DUPLICATES AND THE AVG, MIN AND MAX SALARY FOR EACH ONE OF THEM
SELECT JOB_ID, AVG(SALARY), MAX(SALARY), MIN(SALARY), COUNT(*) FROM EMPLOYEES GROUP BY JOB_ID; -- THIS WILL SHOW ME A LIST OF THE JOB_ID WITHOUT DUPLICATES AND THE AVG, MIN AND MAX SALARY FOR EACH ONE OF THEM, THE COUNT (*) WILL PROVIDE ME THE AMOUNT OF EMPLOYEES I HAVE ON EACH GROUP (JOB_ID)
SELECT JOB_ID, AVG(SALARY), MAX(SALARY), MIN(SALARY), COUNT(*) FROM EMPLOYEES GROUP BY JOB_ID ORDER BY JOB_ID; -- THIS WILL SHOW ME A LIST OF THE JOB_ID WITHOUT DUPLICATES AND THE AVG, MIN AND MAX SALARY FOR EACH ONE OF THEM, THE COUNT (*) WILL PROVIDE ME THE AMOUNT OF EMPLOYEES I HAVE ON EACH GROUP (JOB_ID)
-- I CANNOT SORT IT BY A TAB THAT IS NOT VISIBLE

--Display sum of salary of each department_id
SELECT DEPARTMENT_ID, SUM(SALARY) FROM EMPLOYEES GROUP BY DEPARTMENT_ID;

--Display average of salary of each department_id and round the decimal to be 2
SELECT DEPARTMENT_ID, ROUND(AVG(SALARY),2) FROM EMPLOYEES GROUP BY DEPARTMENT_ID;

--Display avg, max, min, sum of salary and count of each department_id
SELECT DEPARTMENT_ID, ROUND(AVG(SALARY),2), MAX(SALARY), MIN(SALARY), SUM (SALARY), COUNT(*) FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;






